"""rename name columns

Revision ID: 0b205b3e3ac5
Revises: b162b1b42879
Create Date: 2020-09-21 00:57:58.968870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b205b3e3ac5'
down_revision = 'b162b1b42879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('students', sa.Column('last_name', sa.String(), nullable=False))
    op.drop_column('students', 'forename')
    op.drop_column('students', 'surname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('surname', sa.VARCHAR(), nullable=False))
    op.add_column('students', sa.Column('forename', sa.VARCHAR(), nullable=False))
    op.drop_column('students', 'last_name')
    op.drop_column('students', 'first_name')
    # ### end Alembic commands ###
