"""split office

Revision ID: 22be4dd83715
Revises: 03915802ed09
Create Date: 2021-02-23 23:18:25.365050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22be4dd83715'
down_revision = '03915802ed09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('office_building', sa.String(), nullable=True))
    op.add_column('person', sa.Column('office_room', sa.String(), nullable=True))
    op.drop_column('person', 'office')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('office', sa.VARCHAR(), nullable=True))
    op.drop_column('person', 'office_room')
    op.drop_column('person', 'office_building')
    # ### end Alembic commands ###
