"""drop_url_from_profile

Revision ID: 2f2c04a4574c
Revises: dccaddccbbda
Create Date: 2021-03-19 10:26:36.275803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f2c04a4574c'
down_revision = 'dccaddccbbda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('profile_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_url', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
