"""remove eli_whitney

Revision ID: 31fcfd2925ea
Revises: bb2d080aebc3
Create Date: 2022-11-05 00:07:18.891562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31fcfd2925ea'
down_revision = 'bb2d080aebc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('eli_whitney')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eli_whitney', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
