"""departmental columns

Revision ID: 3ba9a838aae2
Revises: 16efb9fe176b
Create Date: 2021-03-15 21:36:16.087422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ba9a838aae2'
down_revision = '16efb9fe176b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('cv', sa.String(), nullable=True))
    op.add_column('person', sa.Column('education', sa.String(), nullable=True))
    op.add_column('person', sa.Column('profile_url', sa.String(), nullable=True))
    op.add_column('person', sa.Column('publications', sa.String(), nullable=True))
    op.add_column('person', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'website')
    op.drop_column('person', 'publications')
    op.drop_column('person', 'profile_url')
    op.drop_column('person', 'education')
    op.drop_column('person', 'cv')
    # ### end Alembic commands ###
