"""add directory columns

Revision ID: 4671021bf1c5
Revises: e9758da8cf25
Create Date: 2020-09-19 02:51:17.909101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4671021bf1c5'
down_revision = 'e9758da8cf25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('netid', sa.String(), nullable=True))
    op.add_column('students', sa.Column('upi', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'upi')
    op.drop_column('students', 'netid')
    # ### end Alembic commands ###
