"""init

Revision ID: 522916eb0691
Revises: 
Create Date: 2021-02-15 15:22:26.764954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522916eb0691'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('netid', sa.String(), nullable=True),
    sa.Column('upi', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('suffix', sa.String(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('college', sa.String(), nullable=True),
    sa.Column('pronoun', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('residence', sa.String(), nullable=True),
    sa.Column('building_code', sa.String(), nullable=True),
    sa.Column('entryway', sa.String(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('suite', sa.Integer(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('birthday', sa.String(), nullable=True),
    sa.Column('major', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('access_code', sa.String(), nullable=True),
    sa.Column('leave', sa.Boolean(), nullable=True),
    sa.Column('eli_whitney', sa.Boolean(), nullable=True),
    sa.Column('primary_organization_code', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('unit_id', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('school_code', sa.String(), nullable=True),
    sa.Column('college_code', sa.String(), nullable=True),
    sa.Column('curriculum', sa.String(), nullable=True),
    sa.Column('office', sa.String(), nullable=True),
    sa.Column('mailbox', sa.String(), nullable=True),
    sa.Column('postal_address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('registered_on', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('person')
    # ### end Alembic commands ###
