"""add residence

Revision ID: 5ebf25951748
Revises: c7003e3f3794
Create Date: 2020-09-19 15:49:38.619053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ebf25951748'
down_revision = 'c7003e3f3794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('residence', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'residence')
    # ### end Alembic commands ###
