"""add access_code

Revision ID: 6c7951d60cb9
Revises: 5ebf25951748
Create Date: 2020-09-19 16:09:28.992890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c7951d60cb9'
down_revision = '5ebf25951748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('access_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'access_code')
    # ### end Alembic commands ###
