"""Add groups

Revision ID: bb2d080aebc3
Revises: 622a48ce91f0
Create Date: 2022-09-03 00:06:12.352665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2d080aebc3'
down_revision = '622a48ce91f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('mission', sa.String(), nullable=True),
    sa.Column('benefits', sa.String(), nullable=True),
    sa.Column('goals', sa.String(), nullable=True),
    sa.Column('constitution', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leadership',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leadership')
    op.drop_table('group')
    # ### end Alembic commands ###
