"""add phone

Revision ID: c7003e3f3794
Revises: 4671021bf1c5
Create Date: 2020-09-19 15:39:28.166881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7003e3f3794'
down_revision = '4671021bf1c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'phone')
    # ### end Alembic commands ###
