"""rename organization_id to organization_code

Revision ID: d7513081cc9c
Revises: a4a1da62f020
Create Date: 2021-02-24 00:04:16.997414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7513081cc9c'
down_revision = 'a4a1da62f020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('organization_code', sa.String(), nullable=True))
    op.drop_column('person', 'organization_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('organization_id', sa.VARCHAR(), nullable=True))
    op.drop_column('person', 'organization_code')
    # ### end Alembic commands ###
