"""add eli_whitney column

Revision ID: f58fc2cc43f6
Revises: 0148ba3fe8f2
Create Date: 2020-09-27 15:13:55.242235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58fc2cc43f6'
down_revision = '0148ba3fe8f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('eli_whitney', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'eli_whitney')
    # ### end Alembic commands ###
