"""add_persistent

Revision ID: f670f536d349
Revises: 31fcfd2925ea
Create Date: 2024-03-18 15:21:14.671517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f670f536d349'
down_revision = '31fcfd2925ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_persistent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('socials_instagram', sa.String(), nullable=True),
    sa.Column('socials_snapchat', sa.String(), nullable=True),
    sa.Column('privacy_hide_image', sa.Boolean(), nullable=True),
    sa.Column('privacy_hide_email', sa.Boolean(), nullable=True),
    sa.Column('privacy_hide_room', sa.Boolean(), nullable=True),
    sa.Column('privacy_hide_phone', sa.Boolean(), nullable=True),
    sa.Column('privacy_hide_address', sa.Boolean(), nullable=True),
    sa.Column('privacy_hide_major', sa.Boolean(), nullable=True),
    sa.Column('privacy_hide_birthday', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_persistent')
    # ### end Alembic commands ###
