"""rename pronoun to pronouns

Revision ID: f8daefdbbc36
Revises: daba3b908152
Create Date: 2021-03-19 19:04:07.372011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8daefdbbc36'
down_revision = 'daba3b908152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pronouns', sa.String(), nullable=True))
        batch_op.drop_column('pronoun')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pronoun', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('pronouns')

    # ### end Alembic commands ###
